openapi: 3.0.0
info:
  version: "1.0.0"
  description: "A REST API service that accepts HTML content in the request payload and responds with the generated PDF content in binary form(as a blob or byte array). This service is powered by iText 7 with the pdfHTML add-on for HTML-to-PDF conversion."
  title: "iText - HTML to PDF API Service"
  termsOfService: "http://swagger.io/terms/"
  contact:
    name: "Ramakrishnan Kuppusami"
    email: "Ramkrishnan.Kuppusami@cdw.com"
servers:
  - url: https://devapps.utcourts.gov/html-to-pdf
  - url: http://devapps.utcourts.gov/html-to-pdf
tags:
  - name: HtmlToPDF
    description:
      A conversion service
paths:
  /convert:
    post:
      operationId: convertHtmlToPdf
      summary: Upload an HTML file and receive the converted PDF file.
      tags:
        - HtmlToPDF
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/HtmlToPdfRequest'
          application/octet-stream:
            schema:
              $ref: '#/components/schemas/HtmlToPdfRequest'
      responses:
        '200':
          description: Successfully converted HTML to PDF
          content:
            application/pdf:
              schema:
                $ref: '#/components/schemas/HtmlToPdfResponse'
        '400':
          description: 400 BAD REQUEST
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BadRequestError'
        '413':
          description: 413 Max File Size Reached
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MaxUploadSizeExceededError'
        '415':
          description: 415 Unsupported input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnsupportedRequestError'
        '500':
          description: Server error while converting HTML to PDF
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerError'

# Schema Definition starts here
components:
  schemas:
    ## Common schema definition - START ##
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
    SuccessResponse:
      type: object
      properties:
        success:
          type: boolean
          default: true
        data:
          type: object
    ErrorResponse:
      type: object
      properties:
        success:
          type: boolean
          default: false
        error:
          $ref: '#/components/schemas/Error'
        statusCode:
          type: integer
    BadRequestError:
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
        - properties:
            statusCode:
              type: integer
              default: 400
    MaxUploadSizeExceededError:
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
        - properties:
            statusCode:
              type: integer
              default: 413
    UnsupportedRequestError:
      allOf:
        - $ref: '#/components/schemas/ErrorResponse'
        - properties:
            statusCode:
              type: integer
              default: 415
    InternalServerError:
      allOf:
        - $ref: '#/definitions/ErrorResponse'
        - properties:
            statusCode:
              type: integer
              default: 500
    ## Common schema definition - END ##
  
    ## HTML To PDF schema definition - START ##
    HtmlToPdfRequest:
      type: object
      properties:
        file:
          type: string
          format: binary
          description: The HTML file to be converted.
  
    HtmlToPdfResponse:
      type: string
      format: binary
      description: The converted PDF file.
    ## HTML To PDF schema definition - END ##
